name: Demo
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create multi-node KinD cluster
        uses: wolkenwalze/actions/kind@main
      - name: Apply test workload
        run: kubectl apply -f demo.yml
      - name: Install Go
        uses: actions/setup-go@v3
      - name: Download Wolkenwalze
        run: |
          wget https://github.com/wolkenwalze/engine/releases/download/v0.0.2/engine_0.0.2_Linux_x86_64.tar.gz
          tar -xvzf engine_0.0.2_Linux_x86_64.tar.gz
      - name: Run Wolkenwalze
        run: |
          ./engine
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wolkenwalze-result
          path: wolkenwalze.json
