name: Demo
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create multi-node KinD cluster
        uses: wolkenwalze/actions/kind@main
      - name: Apply test workload
        run: kubectl apply -f demo.yml
      - name: Install Go
        uses: actions/setup-go@v3
      - name: Run Wolkenwalze
        run: |
          git clone https://github.com/wolkenwalze/engine.git
          cd engine && go build -o wolkenwalze . && cd .. && ./engine/wolkenwalze
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wolkenwalze-result
          path: wolkenwalze.json
