name: Demo
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create multi-node KinD cluster
        uses: wolkenwalze/actions/kind@main
      - name: Apply test workload
        run: kubectl apply -f demo.yml
      - name: Wait  for service to be up
        run: sleep 60
      - name: Install Go
        uses: actions/setup-go@v3
      - name: Download Wolkenwalze
        run: |
          export VERSION=0.0.5
          wget https://github.com/wolkenwalze/engine/releases/download/v${VERSION}/engine_${VERSION}_Linux_x86_64.tar.gz
          tar -xvzf engine_${VERSION}_Linux_x86_64.tar.gz
      - name: Run Wolkenwalze
        run: |
          ./engine
      - name: Generate summary
        if: always()
        run: |
          URL="https://wolkenwalze.github.io/ui/#$(cat wolkenwalze.json | base64 -w 0)"
          echo "[Click here to analyze your results with the Wolkenwalze UI](${URL})" >>$GITHUB_STEP_SUMMARY
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: wolkenwalze-result
          path: wolkenwalze.json
